# Generated by Django 4.0.2 on 2022-02-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='field_1', max_length=200)),
                ('email', models.EmailField(default='field_2', max_length=254)),
                ('password', models.CharField(default='field_3', max_length=50)),
            ],
        ),
    ]
